"use client";

import { useActionState, useState, useTransition } from "react";
import { A } from "@/lib/admin/strings";
import { startEnrol, verifyCode, type MfaState } from "../actions";

export function MfaForm({ verifiedFactorId }: { verifiedFactorId?: string }) {
  const [enrol, setEnrol] = useState<MfaState>({});
  const [starting, startTransition] = useTransition();
  const [state, action, pending] = useActionState<MfaState, FormData>(verifyCode, {});
  const factorId = verifiedFactorId ?? enrol.factorId;

  if (!factorId) {
    return (
      <div className="flex flex-col gap-3">
        {enrol.error && <p role="alert" className="text-danger">{A.mfa.errors.unknown}</p>}
        <button
          type="button"
          disabled={starting}
          onClick={() => startTransition(async () => setEnrol(await startEnrol()))}
          className="min-h-[var(--tap-min)] rounded-md bg-accent px-4 font-semibold text-on-accent disabled:opacity-70"
        >
          {A.mfa.setupButton}
        </button>
      </div>
    );
  }

  return (
    <form action={action} className="flex flex-col gap-4">
      {enrol.qr && (
        <div className="flex flex-col gap-2">
          <p className="text-sm">{A.mfa.scan}</p>
          {/* QR is an SVG data URL generated by Supabase for this user. */}
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={enrol.qr} alt="" width={180} height={180} className="rounded-md border border-line bg-white p-2" />
          <p className="text-sm text-muted">
            {A.mfa.secret}: <code className="break-all font-semibold text-ink">{enrol.secret}</code>
          </p>
        </div>
      )}
      {state.error && (
        <p role="alert" className="rounded-md border-2 border-danger bg-danger-soft p-3 text-sm">
          {A.mfa.errors[state.error] ?? A.mfa.errors.unknown}
        </p>
      )}
      <input type="hidden" name="factorId" value={factorId} />
      <label className="flex flex-col gap-1">
        <span className="font-medium">{A.mfa.code}</span>
        <input name="code" inputMode="numeric" autoComplete="one-time-code" pattern="\d{6}" maxLength={6} required
          className="w-40 rounded-sm border border-line bg-surface px-3 py-2.5 text-lg tracking-widest tabular-nums" />
      </label>
      <button disabled={pending} className="min-h-[var(--tap-min)] rounded-md bg-accent font-semibold text-on-accent disabled:opacity-70">
        {A.mfa.verify}
      </button>
    </form>
  );
}
