-- LandDoctor database setup. Generated by scripts/build-setup-sql.sh — do not edit by hand.
-- Paste into Supabase → SQL Editor → New query, then Run. Run it only once on a new project.
begin;

-- ===== 0001_schema.sql =====
-- LandDoctor Phase 1 — schema.
-- Security rule for every migration: the API roles (anon, authenticated) get NO table
-- privileges. Visitors use narrow security-definer functions; staff use RLS policies.

create schema if not exists private;
revoke all on schema private from public;

-- Supabase grants everything in public to the API roles by default. Undo that for
-- anything this migration owner creates from now on.
alter default privileges in schema public revoke all on tables from anon, authenticated;
alter default privileges in schema public revoke all on sequences from anon, authenticated;
alter default privileges in schema public revoke execute on functions from public, anon, authenticated;

-- Enums ---------------------------------------------------------------------------
create type public.case_status as enum
  ('new', 'triage_done', 'offer_sent', 'paid', 'in_progress', 'delivered', 'closed', 'cancelled', 'refunded');
create type public.area as enum ('savar', 'gazipur', 'other');
create type public.problem_category as enum
  ('pre_purchase_check', 'mutation', 'survey', 'inheritance', 'record_correction', 'dispute');
create type public.contact_pref as enum ('call', 'whatsapp');
create type public.employment_status as enum ('private', 'government_sanctioned');
create type public.consultant_role as enum ('surveyor', 'retired_official', 'advocate', 'deed_writer');
create type public.staff_role as enum ('operations', 'super_admin');
create type public.payment_status as enum ('pending', 'paid', 'failed', 'refunded');
create type public.payment_method as enum
  ('sslcommerz', 'manual_bkash', 'manual_nagad', 'manual_bank', 'manual_cash_office');
create type public.complaint_status as enum ('open', 'resolved');
create type public.event_kind as enum ('created', 'status', 'assign', 'offer', 'payment', 'refund', 'note');

-- Normalised Bangladeshi mobile number, e.g. +8801712345678.
create domain public.bd_mobile as text check (value ~ '^\+8801[3-9][0-9]{8}$');

-- Helpers ------------------------------------------------------------------------
create function private.touch_updated_at() returns trigger
language plpgsql set search_path = '' as $$
begin
  new.updated_at := now();
  return new;
end $$;

create sequence public.case_ref_seq;

-- LD-0001 … LD-9999, then LD-10000 (lpad alone would truncate).
create function private.next_case_ref() returns text
language sql volatile set search_path = '' as $$
  select 'LD-' || case when n < 10000 then lpad(n::text, 4, '0') else n::text end
  from (select nextval('public.case_ref_seq') as n) s
$$;

-- Tables -------------------------------------------------------------------------
create table public.staff (
  user_id uuid primary key references auth.users (id) on delete cascade,
  name text not null check (char_length(name) between 2 and 80),
  role public.staff_role not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.consultants (
  id bigint generated always as identity primary key,
  name text not null check (char_length(name) between 2 and 80),
  role public.consultant_role not null,
  employment_status public.employment_status not null default 'private',
  sanction_ref text,
  conflict_upazilas text[] not null default '{}',
  areas public.area[] not null default '{}',
  upazilas text[] not null default '{}',
  specialities text[] not null default '{}',
  languages text[] not null default '{bn}',
  phone public.bd_mobile not null,
  payout_account text check (payout_account is null or char_length(payout_account) <= 120),
  share_pct int not null default 80 check (share_pct between 0 and 100),
  verified boolean not null default false,
  active boolean not null default true,
  is_demo boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint government_needs_sanction
    check (employment_status = 'private' or char_length(coalesce(sanction_ref, '')) > 0)
);

create table public.packages (
  id bigint generated always as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  name_bn text not null,
  name_en text not null,
  scope_bn text not null,
  scope_en text not null,
  exclusions_bn text not null default '',
  exclusions_en text not null default '',
  delivery_days int not null check (delivery_days between 0 and 60),
  base_price int not null check (base_price >= 0),
  consultant_share_pct int not null check (consultant_share_pct between 0 and 100),
  field_work boolean not null default false,
  price_confirmed boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.cases (
  id bigint generated always as identity primary key,
  ref text not null unique default private.next_case_ref(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  category public.problem_category not null,
  area public.area not null,
  upazila text not null check (char_length(upazila) between 2 and 60),
  mouza text check (mouza is null or char_length(mouza) <= 60),
  documents text[] not null default '{}'
    check (documents <@ array['deed', 'khatian', 'mutation_dcr', 'tax_receipt', 'mouza_map']::text[]),
  description text not null default '' check (char_length(description) <= 1000),
  customer_name text not null check (char_length(customer_name) between 2 and 80),
  customer_phone public.bd_mobile not null,
  contact_pref public.contact_pref not null,
  status public.case_status not null default 'new',
  consultant_id bigint references public.consultants (id),
  source text not null default 'web' check (source in ('web', 'phone', 'whatsapp')),
  idempotency_key uuid unique,
  constraint field_work_in_pilot_area
    check (category not in ('survey', 'pre_purchase_check') or area <> 'other')
);

create table public.offers (
  id bigint generated always as identity primary key,
  case_id bigint not null references public.cases (id),
  package_id bigint not null references public.packages (id),
  consultant_id bigint not null references public.consultants (id),
  token text not null unique check (char_length(token) >= 32),
  service_price int not null check (service_price >= 0),
  govt_fees int not null default 0 check (govt_fees >= 0),
  govt_fees_note text not null default '' check (char_length(govt_fees_note) <= 300),
  price_confirmed boolean not null,
  expires_at timestamptz not null,
  created_by uuid references public.staff (user_id),
  created_at timestamptz not null default now(),
  paid_at timestamptz,
  withdrawn_at timestamptz
);
-- At most one live (unpaid, not withdrawn) offer per case.
create unique index offers_one_open_per_case on public.offers (case_id)
  where paid_at is null and withdrawn_at is null;

create table public.payments (
  id bigint generated always as identity primary key,
  case_id bigint not null references public.cases (id),
  offer_id bigint references public.offers (id),
  amount int not null check (amount > 0),
  method public.payment_method not null,
  tran_id text not null unique,
  gateway_val_id text,
  status public.payment_status not null default 'pending',
  verified_at timestamptz,
  recorded_by uuid references public.staff (user_id),
  reference text check (reference is null or char_length(reference) <= 120),
  raw jsonb,
  created_at timestamptz not null default now()
);

create table public.payouts (
  id bigint generated always as identity primary key,
  consultant_id bigint not null references public.consultants (id),
  period_start date not null,
  period_end date not null check (period_end >= period_start),
  amount int not null check (amount >= 0),
  case_ids bigint[] not null default '{}',
  paid_at timestamptz,
  recorded_by uuid references public.staff (user_id),
  created_at timestamptz not null default now()
);

create table public.waitlist (
  id bigint generated always as identity primary key,
  created_at timestamptz not null default now(),
  district text not null check (char_length(district) between 2 and 60),
  upazila text not null check (char_length(upazila) between 2 and 60),
  category public.problem_category not null,
  phone public.bd_mobile not null,
  idempotency_key uuid unique
);

create table public.complaints (
  id bigint generated always as identity primary key,
  case_id bigint references public.cases (id),
  phone public.bd_mobile,
  description text not null check (char_length(description) between 1 and 2000),
  status public.complaint_status not null default 'open',
  resolution text check (resolution is null or char_length(resolution) <= 2000),
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by uuid references public.staff (user_id)
);

create table public.case_events (
  id bigint generated always as identity primary key,
  case_id bigint not null references public.cases (id),
  at timestamptz not null default now(),
  actor uuid,
  kind public.event_kind not null,
  from_status public.case_status,
  to_status public.case_status,
  note text check (note is null or char_length(note) <= 2000)
);

create table public.rate_limits (
  ip_hash text not null,
  bucket text not null,
  window_start timestamptz not null,
  count int not null default 0,
  primary key (ip_hash, bucket, window_start)
);

create table public.settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

-- Indexes ------------------------------------------------------------------------
create index cases_status_created_idx on public.cases (status, created_at desc);
create index cases_area_idx on public.cases (area);
create index cases_consultant_idx on public.cases (consultant_id);
create index offers_case_idx on public.offers (case_id);
create index offers_package_idx on public.offers (package_id);
create index offers_consultant_idx on public.offers (consultant_id);
create index offers_created_by_idx on public.offers (created_by);
create index payments_case_idx on public.payments (case_id);
create index payments_offer_idx on public.payments (offer_id);
create index payments_recorded_by_idx on public.payments (recorded_by);
create index payouts_consultant_idx on public.payouts (consultant_id);
create index payouts_recorded_by_idx on public.payouts (recorded_by);
create index complaints_case_idx on public.complaints (case_id);
create index complaints_resolved_by_idx on public.complaints (resolved_by);
create index case_events_case_at_idx on public.case_events (case_id, at);
create index waitlist_area_idx on public.waitlist (district, upazila);

-- Triggers -----------------------------------------------------------------------
create trigger consultants_touch before update on public.consultants
  for each row execute function private.touch_updated_at();
create trigger packages_touch before update on public.packages
  for each row execute function private.touch_updated_at();
create trigger cases_touch before update on public.cases
  for each row execute function private.touch_updated_at();

-- Lock down ----------------------------------------------------------------------
alter table public.staff enable row level security;
alter table public.consultants enable row level security;
alter table public.packages enable row level security;
alter table public.cases enable row level security;
alter table public.offers enable row level security;
alter table public.payments enable row level security;
alter table public.payouts enable row level security;
alter table public.waitlist enable row level security;
alter table public.complaints enable row level security;
alter table public.case_events enable row level security;
alter table public.rate_limits enable row level security;
alter table public.settings enable row level security;

revoke all on all tables in schema public from public, anon, authenticated;
revoke all on all sequences in schema public from public, anon, authenticated;
revoke execute on all functions in schema public from public, anon, authenticated;
revoke execute on all functions in schema private from public, anon, authenticated;

-- ===== 0002_public_api.sql =====
-- Public functions for anonymous visitors. These are the ONLY things the anon role
-- can call. They validate every field, rate-limit by hashed network address, are
-- idempotent on a client-generated key, and never return stored personal data.

-- Converts Bangla digits, strips spaces/dashes/brackets and returns +8801XXXXXXXXX or null.
create function private.normalise_phone(p_input text) returns text
language plpgsql immutable set search_path = '' as $$
declare
  d text;
begin
  if p_input is null then return null; end if;
  d := translate(p_input, '০১২৩৪৫৬৭৮৯', '0123456789');
  d := regexp_replace(d, '[\s\-().]', '', 'g');
  if d ~ '^\+8801[3-9][0-9]{8}$' then return d; end if;
  if d ~ '^8801[3-9][0-9]{8}$' then return '+' || d; end if;
  if d ~ '^01[3-9][0-9]{8}$' then return '+88' || d; end if;
  return null;
end $$;

-- Counts a hit for (ip_hash, bucket) in the current hour; raises rate_limited above p_max.
create function private.hit_rate_limit(p_ip_hash text, p_bucket text, p_max int) returns void
language plpgsql set search_path = '' as $$
declare
  n int;
  w timestamptz := date_trunc('hour', now());
begin
  if p_ip_hash is null or char_length(p_ip_hash) = 0 then
    raise exception 'invalid_input:ip';
  end if;
  insert into public.rate_limits as r (ip_hash, bucket, window_start, count)
  values (p_ip_hash, p_bucket, w, 1)
  on conflict (ip_hash, bucket, window_start) do update set count = r.count + 1
  returning r.count into n;
  if n > p_max then
    raise exception 'rate_limited' using errcode = 'P0001';
  end if;
  -- Housekeeping: old windows are not needed.
  delete from public.rate_limits where window_start < now() - interval '2 days';
end $$;

create function private.require_len(p_value text, p_min int, p_max int, p_field text) returns text
language plpgsql immutable set search_path = '' as $$
declare
  v text := btrim(coalesce(p_value, ''));
begin
  if char_length(v) < p_min or char_length(v) > p_max then
    raise exception 'invalid_input:%', p_field;
  end if;
  return v;
end $$;

create function public.submit_case(
  p_category text,
  p_area text,
  p_upazila text,
  p_district text,
  p_mouza text,
  p_documents text[],
  p_description text,
  p_name text,
  p_phone text,
  p_contact_pref text,
  p_idempotency_key uuid,
  p_ip_hash text
) returns table (ref text, outcome text)
language plpgsql security definer set search_path = '' as $$
declare
  v_category public.problem_category;
  v_area public.area;
  v_contact public.contact_pref;
  v_phone text;
  v_upazila text;
  v_district text;
  v_mouza text;
  v_description text;
  v_name text;
  v_docs text[];
  v_case_id bigint;
  v_ref text;
begin
  if p_idempotency_key is null then raise exception 'invalid_input:idempotency_key'; end if;

  -- A repeated key returns what the first request created, without counting a hit.
  select c.ref into v_ref from public.cases c where c.idempotency_key = p_idempotency_key;
  if found then return query select v_ref, 'case'::text; return; end if;
  perform 1 from public.waitlist w where w.idempotency_key = p_idempotency_key;
  if found then return query select null::text, 'waitlist'::text; return; end if;

  perform private.hit_rate_limit(p_ip_hash, 'submit', 5);

  begin v_category := p_category::public.problem_category;
  exception when others then raise exception 'invalid_input:category'; end;
  begin v_area := p_area::public.area;
  exception when others then raise exception 'invalid_input:area'; end;
  begin v_contact := p_contact_pref::public.contact_pref;
  exception when others then raise exception 'invalid_input:contact_pref'; end;

  v_phone := private.normalise_phone(p_phone);
  if v_phone is null then raise exception 'invalid_input:phone'; end if;

  v_upazila := private.require_len(p_upazila, 2, 60, 'upazila');
  v_name := private.require_len(p_name, 2, 80, 'name');
  v_description := private.require_len(p_description, 0, 1000, 'description');
  v_mouza := nullif(private.require_len(p_mouza, 0, 60, 'mouza'), '');

  v_docs := coalesce(p_documents, '{}');
  if not v_docs <@ array['deed', 'khatian', 'mutation_dcr', 'tax_receipt', 'mouza_map']::text[] then
    raise exception 'invalid_input:documents';
  end if;

  if v_area = 'other' then
    v_district := private.require_len(p_district, 2, 60, 'district');
  end if;

  -- Field work outside the pilot areas goes to the waiting list.
  if v_area = 'other' and v_category in ('survey', 'pre_purchase_check') then
    insert into public.waitlist (district, upazila, category, phone, idempotency_key)
    values (v_district, v_upazila, v_category, v_phone, p_idempotency_key)
    on conflict (idempotency_key) do nothing;
    return query select null::text, 'waitlist'::text;
    return;
  end if;

  insert into public.cases (category, area, upazila, mouza, documents, description,
                            customer_name, customer_phone, contact_pref, idempotency_key)
  values (v_category, v_area,
          case when v_area = 'other' then v_upazila || ', ' || v_district else v_upazila end,
          v_mouza, v_docs, v_description, v_name, v_phone, v_contact, p_idempotency_key)
  returning id, cases.ref into v_case_id, v_ref;

  insert into public.case_events (case_id, kind, to_status, note)
  values (v_case_id, 'created', 'new', 'web');

  return query select v_ref, 'case'::text;
end $$;

create function public.join_waitlist(
  p_district text,
  p_upazila text,
  p_category text,
  p_phone text,
  p_idempotency_key uuid,
  p_ip_hash text
) returns void
language plpgsql security definer set search_path = '' as $$
declare
  v_category public.problem_category;
  v_phone text;
begin
  if p_idempotency_key is null then raise exception 'invalid_input:idempotency_key'; end if;
  perform 1 from public.waitlist w where w.idempotency_key = p_idempotency_key;
  if found then return; end if;

  perform private.hit_rate_limit(p_ip_hash, 'waitlist', 5);

  begin v_category := p_category::public.problem_category;
  exception when others then raise exception 'invalid_input:category'; end;
  v_phone := private.normalise_phone(p_phone);
  if v_phone is null then raise exception 'invalid_input:phone'; end if;

  insert into public.waitlist (district, upazila, category, phone, idempotency_key)
  values (private.require_len(p_district, 2, 60, 'district'),
          private.require_len(p_upazila, 2, 60, 'upazila'),
          v_category, v_phone, p_idempotency_key)
  on conflict (idempotency_key) do nothing;
end $$;

revoke execute on function public.submit_case(text, text, text, text, text, text[], text, text, text, text, uuid, text) from public;
revoke execute on function public.join_waitlist(text, text, text, text, uuid, text) from public;
grant execute on function public.submit_case(text, text, text, text, text, text[], text, text, text, text, uuid, text) to anon, authenticated;
grant execute on function public.join_waitlist(text, text, text, text, uuid, text) to anon, authenticated;

revoke execute on all functions in schema private from public, anon, authenticated;

-- ===== 0003_staff_rls.sql =====
-- Staff access. A staff member counts only when their row is active AND their session
-- is two-step verified (JWT aal = 'aal2'). Everything else sees nothing.

create function private.staff_role() returns public.staff_role
language sql stable security definer set search_path = '' as $$
  select s.role
  from public.staff s
  where s.user_id = (select auth.uid())
    and s.active
    and coalesce((select auth.jwt()) ->> 'aal', '') = 'aal2'
$$;

grant usage on schema private to authenticated;
revoke execute on function private.staff_role() from public, anon;
grant execute on function private.staff_role() to authenticated;

-- Read access for staff --------------------------------------------------------------
grant select on public.cases, public.offers, public.payments, public.payouts, public.waitlist,
  public.complaints, public.case_events, public.consultants, public.packages, public.staff,
  public.settings to authenticated;

create policy staff_read on public.cases for select to authenticated
  using ((select private.staff_role()) is not null);
create policy staff_read on public.offers for select to authenticated
  using ((select private.staff_role()) is not null);
create policy staff_read on public.payments for select to authenticated
  using ((select private.staff_role()) is not null);
create policy staff_read on public.payouts for select to authenticated
  using ((select private.staff_role()) is not null);
create policy staff_read on public.waitlist for select to authenticated
  using ((select private.staff_role()) is not null);
create policy staff_read on public.complaints for select to authenticated
  using ((select private.staff_role()) is not null);
create policy staff_read on public.case_events for select to authenticated
  using ((select private.staff_role()) is not null);
create policy staff_read on public.consultants for select to authenticated
  using ((select private.staff_role()) is not null);
create policy staff_read on public.packages for select to authenticated
  using ((select private.staff_role()) is not null);
create policy staff_read on public.staff for select to authenticated
  using ((select private.staff_role()) is not null);
create policy staff_read on public.settings for select to authenticated
  using ((select private.staff_role()) is not null);

-- Complaints: any verified staff member can log and resolve them ------------------------
grant insert (case_id, phone, description), update (status, resolution, resolved_at, resolved_by)
  on public.complaints to authenticated;
create policy staff_insert on public.complaints for insert to authenticated
  with check ((select private.staff_role()) is not null);
create policy staff_update on public.complaints for update to authenticated
  using ((select private.staff_role()) is not null)
  with check ((select private.staff_role()) is not null);

-- Super admin only: consultants, packages, payouts, settings, staff ---------------------
grant insert, update on public.consultants, public.packages, public.payouts, public.settings,
  public.staff to authenticated;

create policy admin_insert on public.consultants for insert to authenticated
  with check ((select private.staff_role()) = 'super_admin');
create policy admin_update on public.consultants for update to authenticated
  using ((select private.staff_role()) = 'super_admin')
  with check ((select private.staff_role()) = 'super_admin');

create policy admin_insert on public.packages for insert to authenticated
  with check ((select private.staff_role()) = 'super_admin');
create policy admin_update on public.packages for update to authenticated
  using ((select private.staff_role()) = 'super_admin')
  with check ((select private.staff_role()) = 'super_admin');

create policy admin_insert on public.payouts for insert to authenticated
  with check ((select private.staff_role()) = 'super_admin');
create policy admin_update on public.payouts for update to authenticated
  using ((select private.staff_role()) = 'super_admin')
  with check ((select private.staff_role()) = 'super_admin');

create policy admin_insert on public.settings for insert to authenticated
  with check ((select private.staff_role()) = 'super_admin');
create policy admin_update on public.settings for update to authenticated
  using ((select private.staff_role()) = 'super_admin')
  with check ((select private.staff_role()) = 'super_admin');

create policy admin_insert on public.staff for insert to authenticated
  with check ((select private.staff_role()) = 'super_admin');
create policy admin_update on public.staff for update to authenticated
  using ((select private.staff_role()) = 'super_admin')
  with check ((select private.staff_role()) = 'super_admin');

-- Identity columns need sequence usage for inserts.
grant usage on all sequences in schema public to authenticated;
revoke usage on sequence public.case_ref_seq from authenticated;

-- ===== 0004_workflow.sql =====
-- Case workflow. Staff change cases ONLY through these functions, which enforce the
-- allowed transitions, consultant eligibility, the conflict-of-interest rule and pricing
-- rights, and write an audit event for every action.

-- Allowed status moves made by hand. offer_sent, paid and refunded are reached only
-- through create_offer, the payment functions and record_refund.
create table private.case_transitions (
  from_status public.case_status not null,
  to_status public.case_status not null,
  primary key (from_status, to_status)
);
-- transitions:begin (kept in sync with lib/cases/workflow.ts by tests/unit/workflow.test.ts)
insert into private.case_transitions (from_status, to_status) values
  ('new', 'triage_done'),
  ('new', 'cancelled'),
  ('triage_done', 'cancelled'),
  ('offer_sent', 'triage_done'),
  ('offer_sent', 'cancelled'),
  ('paid', 'in_progress'),
  ('in_progress', 'delivered'),
  ('delivered', 'closed');
-- transitions:end

insert into public.settings (key, value) values
  ('allow_government_consultants', 'false'),
  ('offer_valid_days', '7')
on conflict (key) do nothing;

-- Returns the caller's user id if they are verified staff (optionally super admin).
create function private.require_staff(p_super_admin boolean default false) returns uuid
language plpgsql stable set search_path = '' as $$
declare
  r public.staff_role := private.staff_role();
begin
  if r is null or (p_super_admin and r <> 'super_admin') then
    raise exception 'not_authorised' using errcode = '42501';
  end if;
  return (select auth.uid());
end $$;

create function private.log_event(p_case_id bigint, p_actor uuid, p_kind public.event_kind,
  p_from public.case_status, p_to public.case_status, p_note text) returns void
language sql set search_path = '' as $$
  insert into public.case_events (case_id, actor, kind, from_status, to_status, note)
  values (p_case_id, p_actor, p_kind, p_from, p_to, nullif(btrim(coalesce(p_note, '')), ''));
$$;

create function private.lock_case(p_case_id bigint) returns public.cases
language plpgsql set search_path = '' as $$
declare
  c public.cases;
begin
  select * into c from public.cases where id = p_case_id for update;
  if not found then raise exception 'not_found:case'; end if;
  return c;
end $$;

-- 32-character URL-safe random token.
create function private.new_token() returns text
language sql volatile set search_path = '' as $$
  select translate(encode(extensions.gen_random_bytes(24), 'base64'), '+/', '-_')
$$;

-- change_case_status ---------------------------------------------------------------
create function public.change_case_status(p_case_id bigint, p_to text, p_note text)
returns void language plpgsql security definer set search_path = '' as $$
declare
  v_actor uuid := private.require_staff();
  c public.cases := private.lock_case(p_case_id);
  v_to public.case_status;
begin
  begin v_to := p_to::public.case_status;
  exception when others then raise exception 'invalid_input:status'; end;

  if not exists (select 1 from private.case_transitions t
                 where t.from_status = c.status and t.to_status = v_to) then
    raise exception 'invalid_transition:% → %', c.status, v_to;
  end if;
  if v_to = 'in_progress' and c.consultant_id is null then
    raise exception 'consultant_required';
  end if;

  -- Leaving offer_sent withdraws the open offer.
  if c.status = 'offer_sent' then
    update public.offers set withdrawn_at = now()
    where case_id = c.id and paid_at is null and withdrawn_at is null;
  end if;

  update public.cases set status = v_to where id = c.id;
  perform private.log_event(c.id, v_actor, 'status', c.status, v_to, p_note);
end $$;

-- assign_consultant ----------------------------------------------------------------
create function public.assign_consultant(p_case_id bigint, p_consultant_id bigint)
returns void language plpgsql security definer set search_path = '' as $$
declare
  v_actor uuid := private.require_staff();
  c public.cases := private.lock_case(p_case_id);
  k public.consultants;
  v_allow_gov boolean;
  v_case_upazila text;
begin
  if c.status in ('closed', 'cancelled', 'refunded', 'delivered') then
    raise exception 'invalid_status:%', c.status;
  end if;

  select * into k from public.consultants where id = p_consultant_id;
  if not found then raise exception 'not_found:consultant'; end if;

  select coalesce((value)::boolean, false) into v_allow_gov
  from public.settings where key = 'allow_government_consultants';

  if not k.verified or not k.active or k.is_demo
     or (k.employment_status = 'government_sanctioned' and not coalesce(v_allow_gov, false)) then
    raise exception 'consultant_not_eligible';
  end if;

  -- Conflict of interest: no cases from an upazila where they work or have worked.
  v_case_upazila := lower(btrim(split_part(c.upazila, ',', 1)));
  if exists (select 1 from unnest(k.conflict_upazilas) u where lower(btrim(u)) = v_case_upazila) then
    raise exception 'conflict_of_interest';
  end if;

  -- Field work needs a consultant who covers the area.
  if c.category in ('survey', 'pre_purchase_check') and not (c.area = any (k.areas)) then
    raise exception 'outside_consultant_area';
  end if;

  update public.cases set consultant_id = k.id where id = c.id;
  perform private.log_event(c.id, v_actor, 'assign', null, null, k.name);
end $$;

-- create_offer ---------------------------------------------------------------------
-- p_service_price null = package price. Only a super admin may set a different price.
create function public.create_offer(p_case_id bigint, p_package_id bigint, p_service_price int,
  p_govt_fees int, p_govt_fees_note text)
returns text language plpgsql security definer set search_path = '' as $$
declare
  v_actor uuid := private.require_staff();
  v_role public.staff_role := private.staff_role();
  c public.cases := private.lock_case(p_case_id);
  p public.packages;
  v_price int;
  v_token text;
  v_days int;
begin
  -- Expired offers no longer block a new one.
  update public.offers set withdrawn_at = now()
  where case_id = c.id and paid_at is null and withdrawn_at is null and expires_at < now();

  if c.status not in ('new', 'triage_done') then
    raise exception 'invalid_status:%', c.status;
  end if;
  if c.consultant_id is null then raise exception 'consultant_required'; end if;

  select * into p from public.packages where id = p_package_id and active;
  if not found then raise exception 'not_found:package'; end if;

  v_price := coalesce(p_service_price, p.base_price);
  if v_price <> p.base_price and v_role <> 'super_admin' then
    raise exception 'not_authorised:price' using errcode = '42501';
  end if;
  if v_price < 0 or coalesce(p_govt_fees, 0) < 0 then raise exception 'invalid_input:price'; end if;

  select coalesce((value)::int, 7) into v_days from public.settings where key = 'offer_valid_days';
  v_token := private.new_token();

  insert into public.offers (case_id, package_id, consultant_id, token, service_price, govt_fees,
                             govt_fees_note, price_confirmed, expires_at, created_by)
  values (c.id, p.id, c.consultant_id, v_token, v_price, coalesce(p_govt_fees, 0),
          btrim(coalesce(p_govt_fees_note, '')), p.price_confirmed,
          now() + make_interval(days => coalesce(v_days, 7)), v_actor);

  update public.cases set status = 'offer_sent' where id = c.id;
  perform private.log_event(c.id, v_actor, 'offer', c.status, 'offer_sent', p.name_en);
  return v_token;
end $$;

-- get_offer (public) -----------------------------------------------------------------
create function public.get_offer(p_token text)
returns table (
  ref text, category text, status text,
  package_name_bn text, package_name_en text, scope_bn text, scope_en text,
  exclusions_bn text, exclusions_en text, delivery_days int,
  service_price int, govt_fees int, govt_fees_note text, total int,
  consultant_name text, consultant_role text, consultant_areas text[], consultant_verified boolean,
  expires_at timestamptz, state text)
language sql stable security definer set search_path = '' as $$
  select c.ref, c.category::text, c.status::text,
         p.name_bn, p.name_en, p.scope_bn, p.scope_en, p.exclusions_bn, p.exclusions_en, p.delivery_days,
         o.service_price, o.govt_fees, o.govt_fees_note, o.service_price + o.govt_fees,
         k.name, k.role::text, k.areas::text[], k.verified,
         o.expires_at,
         case
           when o.paid_at is not null then 'paid'
           when o.withdrawn_at is not null or o.expires_at < now() then 'expired'
           when not o.price_confirmed then 'price_unconfirmed'
           else 'open'
         end
  from public.offers o
  join public.cases c on c.id = o.case_id
  join public.packages p on p.id = o.package_id
  join public.consultants k on k.id = o.consultant_id
  where o.token = p_token and char_length(p_token) >= 32
$$;

-- Payments recorded by staff -----------------------------------------------------------
create function private.open_offer(p_case_id bigint) returns public.offers
language plpgsql set search_path = '' as $$
declare
  o public.offers;
begin
  select * into o from public.offers
  where case_id = p_case_id and paid_at is null and withdrawn_at is null
  for update;
  if not found then raise exception 'invalid_status:no_open_offer'; end if;
  return o;
end $$;

create function public.record_manual_payment(p_case_id bigint, p_amount int, p_method text, p_reference text)
returns void language plpgsql security definer set search_path = '' as $$
declare
  v_actor uuid := private.require_staff();
  c public.cases := private.lock_case(p_case_id);
  o public.offers;
  v_method public.payment_method;
begin
  begin v_method := p_method::public.payment_method;
  exception when others then raise exception 'invalid_input:method'; end;
  if v_method = 'sslcommerz' then raise exception 'invalid_input:method'; end if;
  if c.status <> 'offer_sent' then raise exception 'invalid_status:%', c.status; end if;

  o := private.open_offer(c.id);
  if p_amount is distinct from (o.service_price + o.govt_fees) then
    raise exception 'amount_mismatch';
  end if;

  insert into public.payments (case_id, offer_id, amount, method, tran_id, status, verified_at, recorded_by, reference)
  values (c.id, o.id, p_amount, v_method, 'manual-' || o.id, 'paid', now(), v_actor,
          nullif(btrim(coalesce(p_reference, '')), ''));
  update public.offers set paid_at = now() where id = o.id;
  update public.cases set status = 'paid' where id = c.id;
  perform private.log_event(c.id, v_actor, 'payment', c.status, 'paid',
    v_method::text || coalesce(' ' || p_reference, ''));
end $$;

create function public.record_refund(p_case_id bigint, p_note text)
returns void language plpgsql security definer set search_path = '' as $$
declare
  v_actor uuid := private.require_staff();
  c public.cases := private.lock_case(p_case_id);
begin
  if c.status not in ('paid', 'in_progress', 'delivered') then
    raise exception 'invalid_status:%', c.status;
  end if;
  update public.payments set status = 'refunded' where case_id = c.id and status = 'paid';
  update public.cases set status = 'refunded' where id = c.id;
  perform private.log_event(c.id, v_actor, 'refund', c.status, 'refunded', p_note);
end $$;

create function public.add_case_note(p_case_id bigint, p_note text)
returns void language plpgsql security definer set search_path = '' as $$
declare
  v_actor uuid := private.require_staff();
  c public.cases := private.lock_case(p_case_id);
begin
  if char_length(btrim(coalesce(p_note, ''))) = 0 then raise exception 'invalid_input:note'; end if;
  perform private.log_event(c.id, v_actor, 'note', null, null, p_note);
end $$;

-- Grants ------------------------------------------------------------------------------
revoke execute on all functions in schema private from public, anon, authenticated;
grant execute on function private.staff_role() to authenticated;

revoke execute on function public.change_case_status(bigint, text, text) from public;
revoke execute on function public.assign_consultant(bigint, bigint) from public;
revoke execute on function public.create_offer(bigint, bigint, int, int, text) from public;
revoke execute on function public.get_offer(text) from public;
revoke execute on function public.record_manual_payment(bigint, int, text, text) from public;
revoke execute on function public.record_refund(bigint, text) from public;
revoke execute on function public.add_case_note(bigint, text) from public;

grant execute on function public.change_case_status(bigint, text, text) to authenticated;
grant execute on function public.assign_consultant(bigint, bigint) to authenticated;
grant execute on function public.create_offer(bigint, bigint, int, int, text) to authenticated;
grant execute on function public.record_manual_payment(bigint, int, text, text) to authenticated;
grant execute on function public.record_refund(bigint, text) to authenticated;
grant execute on function public.add_case_note(bigint, text) to authenticated;
grant execute on function public.get_offer(text) to anon, authenticated;

-- ===== seed.sql =====
-- Launch packages. Prices are PLACEHOLDERS from the project brief (price_confirmed = false),
-- so offers show "call us to confirm" instead of a Pay button until the founder confirms them.
insert into public.packages (slug, name_bn, name_en, scope_bn, scope_en, exclusions_bn, exclusions_en,
                             delivery_days, base_price, consultant_share_pct, field_work, price_confirmed)
values
  ('session-30',
   '৩০ মিনিটের পরামর্শ', '30-minute session',
   'ফোন বা WhatsApp কলে বিশেষজ্ঞের পরামর্শ, সঙ্গে পরবর্তী করণীয়ের লিখিত সারাংশ।',
   'Advice from an expert by phone or WhatsApp call, plus a short written summary of next steps.',
   'মাঠে যাওয়া, কাগজ তোলা বা আবেদন জমা দেওয়া এর মধ্যে নেই।',
   'Does not include site visits, collecting documents or filing applications.',
   0, 1000, 80, false, false),
  ('field-survey',
   'জমি মাপজোখ', 'Field survey',
   'আমিন সরেজমিনে গিয়ে জমি মাপবেন, সীমানা চিহ্নিত করবেন এবং নকশাসহ লিখিত ফলাফল দেবেন।',
   'A surveyor visits the land, measures it, marks the boundaries and gives a written result with a sketch.',
   'সীমানা নিয়ে বিরোধ মেটানো বা আদালতের কাজ এর মধ্যে নেই। দাম জমির আকার অনুযায়ী বাড়তে পারে।',
   'Does not include settling boundary disputes or court work. Price may rise with the size of the land.',
   5, 6000, 80, true, false),
  ('land-health-report',
   'ল্যান্ড হেলথ রিপোর্ট', 'Land health report',
   'জমি কেনার আগে দলিলের ধারাবাহিকতা, খতিয়ান, নামজারি, খাজনা ও জানা বিরোধ যাচাই করে বাংলায় লিখিত রিপোর্ট।',
   'Before you buy: checks of the deed chain, khatian, mutation, land tax and known disputes, with a written report in Bangla.',
   'এটি মালিকানার নিশ্চয়তা বা আদালতের জন্য আইনি মতামত নয়। সরকারি কপির ফি আলাদা।',
   'Not a guarantee of title or a legal opinion for court. Government copy fees are extra.',
   7, 8000, 70, true, false)
on conflict (slug) do nothing;

commit;
