#!/usr/bin/env bash
# Combines all migrations and the seed into one file to paste into the Supabase SQL editor.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/supabase/setup.sql"
{
  echo "-- LandDoctor database setup. Generated by scripts/build-setup-sql.sh — do not edit by hand."
  echo "-- Paste into Supabase → SQL Editor → New query, then Run. Run it only once on a new project."
  echo "begin;"
  for f in "$ROOT"/supabase/migrations/*.sql; do
    echo; echo "-- ===== $(basename "$f") ====="; cat "$f"
  done
  echo; echo "-- ===== seed.sql ====="; cat "$ROOT/supabase/seed.sql"
  echo; echo "commit;"
} > "$OUT"
echo "wrote $OUT"
